#'原名' = [ '译名', 出现次数 ]

"卓也" = ["卓也", 4402]
"霧子" = ["雾子", 2329]
"リョウ" = ["凉", 1361]
"マヤさん" = ["麻矢小姐", 699]
"渓" = ["溪", 474]
"忠輔" = ["忠辅", 457]
"真琴" = ["真琴", 433]
"社長" = ["社长", 210]
"沙織" = ["沙织", 159]
"ガモさん" = ["蒲生先生", 137]
"ほのか" = ["穗乃香", 104]
"田代" = ["田代", 71]
"男" = ["男", 51]
"雅人" = ["雅人", 41]
"ヒトミ" = ["瞳", 39]
"友人" = ["朋友", 22]
"女性" = ["女性", 17]
"謎の男" = ["谜之男", 11]
"全員" = ["全员", 9]
"不良Ａ" = ["不良Ａ", 7]
"店員さん" = ["店员", 6]
"女の声" = ["女声", 6]
"女将" = ["老板娘", 5]
"少女" = ["少女", 5]
"左の女性" = ["左边的女性", 4]
"中央の男" = ["中间的男人", 3]
"不良Ｂ" = ["不良Ｂ", 3]
"謎の女" = ["谜之女", 3]
"ビラ配り" = ["发传单的人", 2]
"司会" = ["主持人", 2]
"真鈴" = ["真铃", 2]
"右の女性" = ["右边的女性", 1]
"留守電" = ["电话留言", 1]
"新人" = ["新人", 1]
"相手" = ["对方", 1]
