# searchStr 可缩写为 org, replaceStr 可缩写为 rep (译前和译后字典同样适用)
gptDict = [
    # 语义标注

    { org = "[title]", rep = "[title]", note = "场景标题标记，请保留，标记的该行文本是整个场景（后续对话）的标题，非角色对话或旁白" },
    { org = "[select]", rep = "[select]", note = "选项文本标记，请保留，标记的该行是玩家可选择的选项条目，非角色对话或旁白，通常出现在分支节点处" },

    { org = "<", rep = "<", note = "选项开始标志，被<>包裹起来的文本被看作是选择，比如`你好吗？<我很好>，好吧`，`我很好`就是选项文本" },
    { org = ">", rep = ">", note = "选项结束标志" },

    # ----------------------------------
    # 主要角色
    { org = "卓也", rep = "卓也", note = "人名，男，全名“皆川卓也”（皆川 卓也，みながわ たくや），23岁，“ASH办公室”工作的程序员，性格随和、直率，似玩世不恭，实则认真负责，对身边人很关心" },
    { org = "皆川卓也", rep = "皆川卓也", note = "人名全名，男，即“卓也”" },
    { org = "皆川", rep = "皆川", note = "人名姓氏，卓也的姓氏" },
    { org = "皆川さん", rep = "皆川先生", note = "人名，男性，卓也的称呼" },
    { org = "卓也さん", rep = "卓也先生", note = "人名，男性，卓也的称呼" },
    { org = "皆川君", rep = "皆川君", note = "人名，男性，卓也的称呼" },
    { org = "卓也君", rep = "卓也君", note = "人名，男性，卓也的称呼" },
    { org = "皆川先輩", rep = "皆川前辈", note = "人名，男性，卓也的称呼" },
    { org = "タクちゃん", rep = "小卓", note = "人名，男性，卓也的称呼" },
    { org = "ミナガワ", rep = "皆川", note = "人名，男性，卓也的称呼" },
    { org = "ミナガワタクヤ", rep = "皆川卓也", note = "人名全名，男，即“卓也”，旅馆登记用的假名" },
    { org = "イザヤタクヤ", rep = "五佐谷卓也", note = "人名全名，男，即“卓也”，旅馆登记用的假名" },


    { org = "霧子", rep = "雾子", note = "人名，女，全名“七濑雾子”（七瀬 霧子，ななせ きりこ），20岁，短期大学学生，通过介绍来到ASH办公室打工， 认真、礼貌、害羞，对男性有警戒心，真实身份是隐藏身份的舞台剧演员" },
    { org = "七瀬霧子", rep = "七濑雾子", note = "人名全名，女，即“雾子”" },
    { org = "七瀬", rep = "七濑", note = "人名姓氏，雾子的姓氏" },
    { org = "七瀬さん", rep = "七濑小姐", note = "人名，女性，雾子的称呼" },
    { org = "霧子ちゃん", rep = "小雾子", note = "人名，女性，雾子的称呼" },
    { org = "伝説の役者", rep = "传说中的演员", note = "人名，女性，雾子的称呼，外界对雾子的称呼，因为她14岁时主演的戏剧造成了巨大轰动" },


    { org = "真琴", rep = "真琴", note = "人名，女，全名“五佐谷真琴”（五佐谷 真琴，いざや まこと），19岁，凉的妹妹，为了见姐姐从东京来到绫霞音。对姐姐抱有复杂的情感。认真、要强，说话直接。" },
    { org = "五佐谷真琴", rep = "五佐谷真琴", note = "人名全名，女，即“真琴”" },
    { org = "真琴ちゃん", rep = "小真琴", note = "人名，女性，真琴的称呼" },
    { org = "真琴さん", rep = "真琴小姐", note = "人名，女性，真琴的称呼" },


    { org = "リョウ", rep = "凉", note = "人名，女，全名“五佐谷凉”（五佐谷 リョウ，いざや りょう），23岁，真琴的姐姐，在大企业TTL工作的OL。外表出众，性格强势。自信、开放、捉摸不透。看似洒脱，实则内心可能隐藏着孤独和创伤。" },
    { org = "五佐谷リョウ", rep = "五佐谷凉", note = "人名全名，女，即“凉”" },
    { org = "真鈴", rep = "真铃", note = "人名，女性，凉在风俗店工作的时候使用的假名" },
    { org = "マリン", rep = "玛琳", note = "人名，女性，凉在风俗店工作的时候使用的假名" },
    { org = "リョウさん", rep = "凉小姐", note = "人名，女性，凉的称呼" },
    { org = "リョウちゃん", rep = "小凉", note = "人名，女性，凉的称呼" },


    { org = "五佐谷さん", rep = "五佐谷小姐", note = "人名称呼，女性，一般代指凉" },
    { org = "五佐谷", rep = "五佐谷", note = "人名姓氏，真琴和凉的姓氏" },
    { org = "イザヤ", rep = "五佐谷", note = "姓氏（读音）" },


    { org = "忠輔", rep = "忠辅", note = "人名，男，全名“榎本忠辅”（榎本 忠輔，えのもと ただすけ），23岁，卓也从初中开始的好友。一流大学的学生，成绩优异。认真、单纯，在恋爱方面比较笨拙" },
    { org = "榎本忠輔", rep = "榎本忠辅", note = "人名全名，男，即“忠辅”" },
    { org = "榎本", rep = "榎本", note = "人名姓氏，忠辅的姓氏" },
    { org = "榎本君", rep = "榎本君", note = "人名，男性，忠辅的称呼" },
    { org = "榎本さん", rep = "榎本先生", note = "人名，男性，忠辅的称呼" },
    { org = "チュースケ", rep = "小忠", note = "人名，男性，忠辅的称呼" },


    { org = "渓", rep = "溪", note = "人名，男，全名“神岭溪”（神嶺 渓，かみね けい），23岁，雅人的弟弟，在港口附近汽车修理厂工作的机械师。冷静、沉默寡言、可靠。给人一种踏实、成熟的感觉。" },
    { org = "神嶺渓", rep = "神岭溪", note = "人名全名，男，即“溪”" },
    { org = "神嶺", rep = "神岭", note = "人名姓氏，溪的姓氏" },
    { org = "神嶺さん", rep = "神岭先生", note = "人名，男性，溪的称呼" },
    { org = "渓君", rep = "溪君", note = "人名，男性，溪的称呼" },


    { org = "マヤ", rep = "麻矢", note = "人名姓氏，女，麻矢的姓氏" },
    { org = "杏子", rep = "杏子", note = "人名，女，麻矢的名字" },
    { org = "マヤさん", rep = "麻矢小姐", note = "人名称呼，女，全名为“麻矢杏子”（フルネーム），28岁，酒吧“maya”的老板娘，成熟、善于倾听、像大姐姐一样的存在。与社长是旧友。" },
    { org = "麻矢杏子", rep = "麻矢杏子", note = "人名全名，女性，即“麻矢”" },


    { org = "ガモさん", rep = "蒲生先生", note = "人名称呼，男，全名“蒲生广志”（蒲生 広志，がもう ひろし），ASH办公室的同事，已婚。有时会邀请卓也去娱乐场所。" },
    { org = "蒲生", rep = "蒲生", note = "人名姓氏，蒲生的姓氏" },
    { org = "蒲生さん", rep = "蒲生先生", note = "人名，男性，蒲生的称呼" },


    { org = "沙織", rep = "沙织", note = "人名，女，全名“周船寺沙织”（周船寺 沙織，すせんじ さおり）。雾子的朋友（或同行），对雾子的事情非常关心，甚至会来警告卓也。" },
    { org = "周船寺沙織", rep = "周船寺沙织", note = "人名全名，女，即“沙织”" },
    { org = "周船寺", rep = "周船寺", note = "人名姓氏，沙织的姓氏" },
    { org = "沙織さん", rep = "沙织小姐", note = "人名，女性，沙织的称呼" },

    { org = "社長", rep = "社长", note = "人名代称，女性，ASH办公室的社长。对雾子有照顾的责任感" },

    # ----------------------------------
    # 其他术语/角色
    { org = "ＡＳＨ", rep = "ＡＳＨ", note = "小型程序事务所的名字，卓也和雾子工作的程序事务所" },
    { org = "オフィスＡＳＨ", rep = "ＡＳＨ办公室", note = "小型程序事务所的名字，卓也和雾子工作的程序事务所" },

    { org = "ＴＴＬ", rep = "ＴＴＬ", note = "企业名，凉工作的的大企业，是ASH的承包商" },
    { org = "綾霞音", rep = "绫霞音", note = "地名，故事发生的街道名称" },
    { org = "ｍａｙａ", rep = "ｍａｙａ", note = "酒吧名，故事核心的聚集地，大家常去的酒吧。麻矢小姐是老板娘" },
    { org = "ファンテーン・シティ", rep = "凡提恩城", note = "设施名，大型商业设施，内有电影院等" },
    { org = "プロダクション・プラーナ", rep = "普拉纳制作公司", note = "穗乃香所属的制作公司，试图推动雾子重返舞台" },
    { org = "プラーナ", rep = "普拉纳", note = "穗乃香所属的制作公司，试图推动雾子重返舞台" },


    { org = "ランジェリー・パブ『ピーチーズ』", rep = "情趣内衣酒吧『蜜桃』", note = "风俗店名字" },
    { org = "ピーチーズ", rep = "蜜桃", note = "风俗店名字" },

    { org = "九乃坂次郎", rep = "九乃坂次郎", note = "人名，男性，已故的舞台剧剧本巨匠，雾子的父亲。" },


    { org = "田代", rep = "田代", note = "人名（姓氏），男性，全名“田代聪史”（田代聡史，たしろ さとし），TTL的员工，与卓也有工作往来。语气有点独特" },
    { org = "タシロ", rep = "田代", note = "人名，男性，即“田代”" },
    { org = "田代クン", rep = "田代君", note = "人名，男性，田代的称呼" },
    { org = "田代さん", rep = "田代先生", note = "人名，男性，田代的称呼" },


    { org = "ほのか", rep = "穗乃香", note = "人名，女性，全名“槙穗乃香”（槙 ほのか），来自制作公司“普拉纳”(プラーナ)，催促雾子重返舞台" },
    { org = "槙ほのか", rep = "槙穗乃香", note = "人名全名，女性，即“穗乃香”" },
    { org = "槙", rep = "槙", note = "人名姓氏，穗乃香的姓氏" },
    { org = "槙さん", rep = "槙小姐", note = "人名，女性，穗乃香的称呼" },


    { org = "ヒトミ", rep = "瞳", note = "人名，女性，情趣内衣酒吧『蜜桃』的员工" },

    { org = "店員さん", rep = "店员", note = "人物称呼" },
    { org = "司会", rep = "主持人", note = "称呼，性别未知" },

    { org = "女将", rep = "老板娘", note = "称呼，女性，温泉旅馆“城内温泉”的老板娘，讲话客气、周到，有职业性的热情。" },

    { org = "ジョアンナ・サンデー", rep = "乔安娜·桑迪", note = "电影名" },
    { org = "ＬＯＶＥＳＣＡＲＬＥＴ", rep = "爱情猩红", note = "电影名" },


    { org = "一ノ関", rep = "一之关", note = "人名" },

    { org = "ユウサク", rep = "悠作", note = "人名，男性，凉的前男友，因交通事故死亡" },

    { org = "雅人", rep = "雅人", note = "人名，男性，全名“堤雅人”，已婚，溪的哥哥，TTL的部长，傲慢、有权势，喜欢操控他人" },
    { org = "堤雅人", rep = "堤雅人", note = "人名全名，男性，即“雅人”" },
    { org = "堤部長", rep = "堤部长", note = "人名，男性，雅人的称呼" },

]
